export default [
  {
    id: 1,
    img: "./src/assets/card-image.png",
    rating: "5.0",
    reviewCount: "6",
    country: "USA",
    title: "Life lessons with Katie Zaferes",
    price: "136",
    openspots: 0,
  },
  {
    id: 2,
    img: "./src/assets/bike.jpg",
    rating: "6.1",
    reviewCount: "9",
    country: "Rwanda",
    title: "Group Mountain Biking",
    price: "150",
    openspots: 2,
  },
  {
    id: 3,
    img: "./src/assets/teacher.png",
    rating: "4.5",
    reviewCount: "8",
    country: "Spain",
    title: "Learn with teacher mwenyewe",
    price: "120",
    openspots: 10,
  },
  {
    id: 4,
    img: "./src/assets/flower.jpg",
    rating: "5.1",
    reviewCount: "5",
    country: "Italian",
    title: "Learn wedding photography",
    price: "200",
    openspots: 0,
  },
  {
    id: 5,
    img: "./src/assets/students.png",
    rating: "3.8",
    reviewCount: "3",
    country: "Online",
    title: "Learn academics within class",
    price: "100",
    openspots: 17,
  },
];
